### ISSUE TITLE
tables with themes?

### ISSUE THREAD

**Issue by fdncred** [marc2332/freya-visualizer#1]
Can I convince you to update this to the latest version and demonstrate how the themes would work?

**Comment by marc2332** [comment]
> Can I convince you to update this to the latest version and demonstrate how the themes would work?

Of course! I'll do it asap, I got a busy day today

**Comment by marc2332** [comment]
Just pushed some changes adding a nushell-vibes theme, thoughts? :v: For now themes are limited to just colors, I'll improve this in the future

![image](https://github.com/marc2332/freya-visualizer/assets/38158676/9bb5704a-6ec6-40c2-aeb8-b37a8fd8db8b)

**Comment by fdncred** [comment]
ooooh, nice! It looks pretty good! 

As a future improvement, one thing I was going to play with is not sorting the column names because that always throws me off. The columns need to be in the order that nushell passes them. I'm anxious to dig in and learn how you do these things.

**Comment by marc2332** [comment]
> ooooh, nice! It looks pretty good!
> 
> As a future improvement, one thing I was going to play with is not sorting the column names because that always throws me off. The columns need to be in the order that nushell passes them. I'm anxious to dig in and learn how you do these things.

I wasn't actually sorting anything, looks like `serde_json` is actually the one sorting the properties 👀 I wonder if we can do anything about that 🤔

**Comment by marc2332** [comment]
Example:

![image](https://github.com/marc2332/freya-visualizer/assets/38158676/a855bc3f-b117-4311-8e6c-e3d59765e9a7)

![image](https://github.com/marc2332/freya-visualizer/assets/38158676/f74c37d8-55b6-442d-b1fd-4e34476eb124)

**Comment by fdncred** [comment]
Oh, I thought you were sorting here to get a unique list of columns names.
https://github.com/marc2332/freya-visualizer/blob/a903f12bdefa01eaf71748e3697f4e776b319175/src/main.rs#L76-L77

Either way, I would need to figure out a way to just take them as they come. Not sure there's a good way to do that. Also, I'd want to have column text color different from body text. I could probably add a `#` index column pretty easily. Just playing around though.

**Comment by marc2332** [comment]
> Oh, I thought you were sorting here to get a unique list of columns names.

You are 100% right, I forgot that existed! I just pushed some changes, but, we are still limited by the json parser, I'll see what I can do

**Comment by marc2332** [comment]
Nevermind! Just got it working 🚀 Give it a try now :P

**Comment by fdncred** [comment]
yay! Love the order much better!

**Comment by fdncred** [comment]
Why do the header column separators sometimes not line up with the data column separators?
![image](https://github.com/marc2332/freya-visualizer/assets/343840/adb24832-23f8-45aa-852d-8bb8eed0d4a1)

**Comment by marc2332** [comment]
> Why do the header column separators sometimes not line up with the data column separators? ![image](https://user-images.githubusercontent.com/343840/277492691-adb24832-23f8-45aa-852d-8bb8eed0d4a1.png)

Because of the scrollbar 😅 I have yet to think a way of making prettier when the scrollbar is shown, let me know if anything comes to your mind :)

**Comment by fdncred** [comment]
ah, ok. that makes sense at least.

**Comment by fdncred** [comment]
I guess we can close this. Thanks for all you've done here. It's fun to play with!!!

Seems like freya tables is kind of in its infancy but I'd love to use freya to build some fancy table visualizer for nushell. I'm not quite sure how to get there yet. Just spit balling here with some features I'd like to eventually see.

1. More configurable theme for row and column headers.
2. More configurable theme for cells, including fg and bg color, styles like bold, and italic.
3. More configurable theme for alignment, for nushell I think we use alignment based on datatype.
4. Will need to hook into nushell somehow to allow nushell values to be present like human readable file sizeas and human readable dates like nushell does.
5. Ability to sort single columns and multiple columns.
6. Ability to make selections by row header or column header and copy the data for pasting elsewhere.
7. Ability to have nested tables like `sys | to json | freya-visualizer`.
8. Header/Scrollbar misalignment fix.
9. Speed. Would need maybe a virtualized grid for optimal speed. Not sure.

Those are a few items that quickly come to mind. I love what you have so far. Just thinking out loud of what we'd need.

Coming back to this again, most/some of the suggestions may make more sense when you see the `ls` output of nushell, which is kind of what I'm trying to mimic because we would want to give people a familiar looking environment.
![image](https://github.com/marc2332/freya-visualizer/assets/343840/87306d3c-ac05-4538-897c-8859f636393f)

**Comment by marc2332** [comment]
Challenge accepted! I'll try to improve what is currently done and add what is missing 😄 :v: Thanks for the suggestions!
